name: Bug
description: Fehler melden
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: observed
    attributes:
      label: Beobachtet
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartet
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduktion
